name: Run Unit Test via Pytest on Linux, Unix and Windows

on: [push]  

jobs:  
  build:  
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:  
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]  

    steps:  
      - uses: actions/checkout@v1  
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v1  
        with:  
          python-version: ${{ matrix.python-version }}  
          allow-prereleases: true
      - name: Install dependencies (Linux/macOS)
        run: |  
          python -m pip install --upgrade pip  
          python -m venv .ml2sql
          if [ -f docs/requirements-dev.txt ]; then .ml2sql/bin/python -m pip install --index-url https://pypi.org/simple -r docs/requirements-dev.txt; fi  
        shell: bash  # This step uses bash for Linux/macOS
      - name: Install dependencies (Windows)
        run: |  
          # Use powershell commands for Windows
          python -m pip install --upgrade pip  
          python -m venv .ml2sql
          if (Test-Path "docs\requirements-dev.txt") { .ml2sql\Scripts\python.exe -m pip install --index-url https://pypi.org/simple -r "docs\requirements-dev.txt" }
        shell: pwsh  # This step uses powershell for Windows
      - name: Lint with Ruff  
        run: |  
          .ml2sql/bin/ruff check
        continue-on-error: true  
      - name: Test with pytest (Linux/macOS)  
        run: |  
          .ml2sql/bin/coverage run -m pytest  -v -s  
        shell: bash  # This step uses bash for Linux/macOS
      - name: Test with pytest (Windows)  
        run: |  
          # Use powershell equivalent for coverage run
          & .ml2sql\Scripts\coverage.exe run -m pytest  -v -s
        shell: pwsh  # This step uses powershell for Windows
      - name: Generate Coverage Report  
        run: |  
          .ml2sql/bin/coverage report -m
