name: Run Tests via Pytest on Linux, Unix and Windows

on: [push]  

jobs:  
  build:  
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:  
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]  

    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:  
          python-version: ${{ matrix.python-version }}  
      - name:  Install dependencies ${{ matrix.os }}
        run: |
              python -m pip install --upgrade pip  
              python -m venv .ml2sql
              if [ "$RUNNER_OS" == "Windows" ]; then
                    ".ml2sql\Scripts\python" -m pip install --index-url https://pypi.org/simple -r "docs\requirements-dev.txt"
              else
                    .ml2sql/bin/python -m pip install --index-url https://pypi.org/simple -r docs/requirements-dev.txt  
              fi
        shell: bash
      - name: Lint with Ruff  
        run: |
              if [ "$RUNNER_OS" == "Windows" ]; then
                    ".ml2sql\Scripts\ruff" check --output-format=github .
              else
                    .ml2sql/bin/ruff check --output-format=github .
              fi  
        shell: bash 
        continue-on-error: true  
      - name: Test with pytest
        run: |  
              if [ "$RUNNER_OS" == "Windows" ]; then
                    ".ml2sql\Scripts\pytest" -v -k "not _script and not test_pre_process_kfold"
              else
                    source .ml2sql/bin/activate
                    coverage run -m pytest -v
              fi  
        shell: bash 
          
