name: Run Unit Test via Pytest on Linux, Unix and Windows

on: [push]  

jobs:  
  build:  
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:  
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]  

    steps:  
      - uses: actions/checkout@v1  
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:  
          python-version: ${{ matrix.python-version }}  
      - name:  Install dependencies ${{ matrix.os }}
        run:   |
              if [ "$RUNNER_OS" == "Windows" ]; then
                    if (Test-Path "docs\requirements-dev.txt") { .ml2sql\Scripts\python.exe -m pip install --index-url https://pypi.org/simple -r "docs\requirements-dev.txt" }
              else
                    if [ -f docs/requirements-dev.txt ]; then .ml2sql/bin/python -m pip install --index-url https://pypi.org/simple -r docs/requirements-dev.txt; fi  
                    exit 1
              fi
        shell: bash
      - name: Lint with Ruff  
        run: |
              if [ "$RUNNER_OS" == "Windows" ]; then
                    .ml2sql/Scripts/ruff check
              else
                    .ml2sql/bin/ruff check
                    exit 1
              fi  
        shell: bash 
        continue-on-error: true  
      - name: Test with pytest (Linux/macOS)  
        run: |  
              if [ "$RUNNER_OS" == "Windows" ]; then
                    .ml2sql\Scripts\coverage.exe run -m pytest  -v -s
              else
                    .ml2sql/bin/coverage run -m pytest  -v -s  
                    exit 1
              fi  
        shell: bash 
      - name: Generate Coverage Report  
        run: |  
              if [ "$RUNNER_OS" == "Windows" ]; then
                    .ml2sql\Scripts\coverage.exe report -m
              else
                    .ml2sql/bin/coverage report -m
                    exit 1
              fi  
        shell: bash  
          
